Add hyperlinks of stack traces in Laravel logs
JetBrains/ideolog pull request #147
Opened 2023-06-28 09:41 UTC by smirok

2023-06-28 17:19 UTC, smirok commented
<img width="990" alt="Screenshot 2023-06-28 at 19 15 20" src="https://github.com/JetBrains/ideolog/assets/55107433/611ce359-b72c-42f7-90ed-c80c71e58bca">

2023-06-29 10:48 UTC, pestretsov requested changes

2023-06-29 10:48 UTC, pestretsov commented on src/main/kotlin/com/intellij/ideolog/filters/LaravelStackTraceFileFilter.kt
> +    var documentLine = 0
It's always a better idea to declare variables as close to their first usage as possible. Also, let's avoid using `var`s when they are not needed

```
val documentLine = if (possibleDocumentLine != Int.MIN_VALUE) possibleDocumentLine - 1 else possibleDocumentLine
```

2023-06-29 10:48 UTC, pestretsov commented on src/main/kotlin/com/intellij/ideolog/filters/LaravelStackTraceFileFilter.kt
> +    val filePathEndIndex = fileUri.lastIndexOf('(')
Can be inlined, variables with 1 usage and simple right hand side (here we easily understand that .lastIndexOf('(') is actually a file path end index)

2023-06-29 10:48 UTC, pestretsov commented on src/main/kotlin/com/intellij/ideolog/filters/LaravelStackTraceFileFilter.kt
> +    val items = collectItems(textStartOffset, LINUX_MACOS_FILE_PATTERN.matcher(line)) +
`items` and `collectItems` are kinda too generic names, right?

2023-06-29 10:48 UTC, pestretsov commented on src/main/kotlin/com/intellij/ideolog/filters/LaravelStackTraceFileFilter.kt
> +    val items = collectItems(textStartOffset, LINUX_MACOS_FILE_PATTERN.matcher(line)) +
Performance: we probably should add some kind of fast check that line is not Url to avoid checking regexps

2023-06-29 11:37 UTC, smirok commented on src/main/kotlin/com/intellij/ideolog/filters/LaravelStackTraceFileFilter.kt
> +    val filePathEndIndex = fileUri.lastIndexOf('(')
`filePathEndIndex` has 2 usages and I've decided to put it in a variable

2023-06-30 07:49 UTC, closed without merging